### ISSUE TITLE
Support Yarn Berry (Without PNP)

### ISSUE THREAD

**Issue by yovanoc** [gqless/gqless#150]
![image](https://user-images.githubusercontent.com/7302317/112287815-0eb5b980-8c8d-11eb-8c6d-05707ba47e35.png)

With yarn berry with `nodeLinker: node-modules` it does not work :/

**Comment by PabloSzx** [comment]
thanks for reporting it, soon I'm going to be looking into it

**Comment by PabloSzx** [comment]
Found the issue, it's basically an error of yarn, since it doesn't understand this:

![image](https://user-images.githubusercontent.com/8672915/112401720-ec05be00-8ce9-11eb-80ed-832bd647480c.png)

Which is basically to support both "npx @gqless/cli generate" and "npx gqless generate", but I guess it's not a big deal to just remove it to ensure support of `yarn berry`

Which btw I tested and works as expected with both pnp on & off.
