### ISSUE TITLE
[BUG] preImport not working

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#182]
"gqless": "^2.0.11",
"@gqless/cli": "^2.0.14",

gqless.config.cjs:

```js
const config = {
	endpoint: '/api/graphql',
	enumsAsStrings: false,
	react: true,
	scalars: { AWSDateTime: 'string' },
	preImport: `
		scalar AWSDateTime
	`,
	introspection: {
		endpoint: './amplify/backend/api/demo/build/schema.graphql',
		headers: {},
	},
	destination: './src/gqless/index.ts',
	subscriptions: false,
};

module.exports = config;
```

schema.graphql
```graphql
type Todo {
  id: ID!
  name: String!
  description: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

![image](https://user-images.githubusercontent.com/69426460/114006443-1c606700-9869-11eb-90ab-ce8038f06d1c.png)

**Comment by MaxmaxmaximusAWS** [comment]
solution
---

You must first concatenate the preImport string, and only then parse the resulting "file" content.

**Comment by MaxmaxmaximusAWS** [comment]
Oh, is this preImport field placed in the typescript code and not at the beginning of the schema.graphql file? =)) Please add a preSchema field or something like that where you could define your additional scalars that are not listed in the main schema. Well, or just give the opportunity to set SEVERAL schema files)

**Comment by PabloSzx** [comment]
gqless never creates a "schema.graphql" file, it only creates the destination specified in the config and the schema.generated.ts besides the destination file itself, and the preImport is only meant to be for the auto-generated schema.generated.ts, since it's always overwritten, and the file itself says you shouldn't overwrite the schema.generated.

The other thing, gqless only uses whatever the API says it has, and the "scalars" field in the config is meant for the translation of the scalars in graphql to typescript, not for creation of scalars whatsoever

**Comment by PabloSzx** [comment]
> Well, or just give the opportunity to set SEVERAL schema files)

gqless is not meant to do schema stitching, it's only for using an existing API, if the API itself is not using a scalar it should respect it, and if you want to map the scalars to the ts type, use the "scalars" config.

**Comment by MaxmaxmaximusAWS** [comment]
I agree, gqless should not fix a flawed schema
