### ISSUE TITLE
[FEATURE] Please add watch mode

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#183]
Please add watch mode =)

**Comment by PabloSzx** [comment]
If you have the API serving the API/schema besides your client, you can easily use the programmatic API https://gqless.com/cli/programmatic
We have already been using it and it works great, a watch mode doesn't have much sense in any other scenario other than trying to sync an automated output from another living instance, and for that, the programmatic API does the job way cleaner, for any other purpose, watch mode doesn't have any sense, since it would be literally just polling a graphql API for a 99.99% of no-change detection, it would be just unnecessary load for API.

**Comment by MaxmaxmaximusAWS** [comment]
@PabloSzx You said that people use the http endpoint 99% of the time, and this is the reason not to support specifying a schema file. but @ gqless / cli has support for specifying a schema file.

Consequently, 1% usage does not stop you from supporting file introspection, therefore you can add the watch option to change the file, or pollyInteval: 0.5 seconds if the http scheme is specified

Why isn't 1% usage stopping you from "adding file link support", and why is that little 1% usage stopping you from adding "watch mode"?

**Comment by MaxmaxmaximusAWS** [comment]
P.S. Your project is amazing, today I showed it to my colleague from AWS, he is also delighted, I’ll figure out what can be done with this and how to integrate it into AWS AppSync, but after today's discussion, we agreed that the problem of AWS AppSync is in its monolithic nature, and it will be needed where then half a year to add an interlayer like Relay =), in general, I am very impressed with your development of the guys, tell me how to become your personal sponsor not on behalf of a company, but on behalf of a person.

**Comment by samdenty** [comment]
I think a watch mode does make sense, querying the API excessively could be an issue (GitHub rate-limits you).

A new subcommand such as `gqless watch`, would work as it'd be clear what it's doing.

For URLs that resolve to `localhost` / `127.0.0.1`, polling every 200ms should be sufficient, other urls every 5 seconds.

**Comment by ericwooley** [comment]
You could probably just use this https://www.npmjs.com/package/forever, and essentailly poll

**Comment by samdenty** [comment]
Closing in favour of #194
