### ISSUE TITLE
Support for hooks

### ISSUE THREAD

**Issue by vektah** [gqless/gqless#40]
This library looks amazing, first time I've felt excited to write react in a while. tada

How difficult would it be to support hooks instead of HOCs?

```ts
function User({ user }: { user: User }) {
  useGraphql();

  return (
    <div>
      <h2>
        {user.name}
      </h2>
      <img src={user.avatarUrl({ size: 100 })} />
    </div>
  );
}
```
instead of

```ts
const User = graphql(({ user }: { user: User }) =>
  <div>
    <h2>
      {user.name}
    </h2>
    <img src={user.avatarUrl({ size: 100 })} />
  </div>
);
```
It might even provide a nice way to put query into scope:

```ts
function App() {
  const { query } = useGraphql();

  return (
    <div>
      <h1>
        {query.me.name}
      </h1>
      <Query>
        <Description user={query.me} />
      </Query>
    </div>
  );
}
```

**Comment by samdenty** [comment]
I did think about using hooks instead of a HoC, but it has limitations:

- Hooks wouldn't be auto-typed, unless re-exported from the client / using generics.


- Hooks wouldn't allow automatic component updates.
In your third example, `Description` wouldn't be able to update when `query.me` changes

- Wouldn't allow for a single-phase suspense render
If we simply threw a promise when you access `query.me.name`, then we'd have to render X times.
This is solved with the `graphql` wrapper, instead returning a fragment with a component that suspends. This way, your entire apps renders before suspending

- Wouldn't allow named queries / query merging
The GraphQL component automatically wraps your component in context. This is can be used to orchestrate queries in any way possible.

**Comment by samdenty** [comment]
Ultimately they could be partially supported, but it would be way more verbose and feel less-magic

Through the `babel-plugin` I've thought about automatically wrapping components, so you don't need to. This could be implemented once #39 ships, but that's going to take a while

**Comment by vektah** [comment]
Yeah my thoughts are mostly asthetic, I find working with hocs a little frustrating at times. For example the hook api to react-router is 1000x better than the hoc one. 

Sounds like the opposite is true here though, mostly because its not just plumbing data out of context.

> Through the babel-plugin I've thought about automatically wrapping components, so you don't need to. This could be implemented once #39 ships, but that's going to take a while

That sounds :100:

**Comment by migueloller** [comment]
I will say that the urge to use hooks vs HOCs is mostly a matter of aesthetics or perhaps the idea that it's more "idiomatic" react, which isn't necessarily justified in changing the API.

But, having said that... could the points you made be solved as follows?

- Couldn't the auto-typing be achieved by having a potential `useQuery` hook return the hook from the created gqless client? If the client is exposed via context and this context's value is typed just as `client.query` is, shouldn't the returned value of the hook be typed as well?
- The same way the HOC re-renders the component, can't the hook trigger an update as well (i.e., how `useState` does) when the value of `query.me` changes?
- Don't know enough about the current solution to have a hooks alternative for this one.
- Since there's wrapping going on when using the `Query` component anyway, couldn't that be used as the context boundary instead of the `graphql` HOC?

cc: @samdenty

**Comment by samdenty** [comment]
`graphql()` is needed for the custom suspense rendering to work. It's not really a HoC in the conventional sense. Hooks make the API harder to use

I'm pretty much using it for the same purpose as https://github.com/mobxjs/mobx-react-lite, which uses `observer`

```js
const Calculator = observer(({ hasExploded }: { hasExploded: boolean }) => {
```

I guess I could add support for their `useObserver` pattern.

**Comment by dai-shi** [comment]
I don't mean to replace the HoC API, but developed a hook out of my curiosity. https://github.com/dai-shi/gqless-hook

> Hooks wouldn't be auto-typed, unless re-exported from the client / using generics.

I made it to receive `client`. We could create a typed context and use it, but it would require re-exporting a custom hook.

**Comment by samdenty** [comment]
The main reason why I don't want to officially support hooks, is that you would have to manually subscribe for reactivity.

```ts
const Story: React.FC<Props> = ({ story }) => (
  <article>
    {story.url} // If story.url is updated in the Cache, how is the update propagated to the Story component?
  </article>
);

const TopStories: React.FC = () => {
  const query = useQuery(client);
  return (
    <div>
      {query.hn?.topStories({ limit: 25 })?.map((story) => (
        story && <Story key={story.id} story={story} />
      ))}
    </div>
  );
};
```

the `graphql()` HoC can automatically do this, because it intercepts the Proxy lookups during the render:

```ts
const Story = graphql(({ story }) => (
  // START INTERCEPTING
  <article>
    {story.url}
  </article>
  // END INTERCEPTING
  // ACCESSORS = [story.url]
));
```

without the ability to "observe" what's accessed during render, you'd have to do something like:

```ts
const Story = graphql(({ story }) => {
  useObserver(story.url)

  return <article>
    {story.url}
  </article>
});
```

**Comment by dai-shi** [comment]
Yeah, you can't only re-render `Story`, but you would re-render the whole tree from `TopStories`. I think it's OK as long as we could wrap `Story` with React.memo.

"render-based observer" is technically possible (with some limitations). I've done lots of work in my project: https://github.com/dai-shi/react-tracked
(I've also done experiment for mobx without useObserver.)

I will later try and see how reactivity works or not.

**Comment by samdenty** [comment]
> re-render the whole tree from TopStories

Don't think that would work as `story={story}` would always maintain the same identity (accessors are mutable references, not immutable).
*though may currently work, cause I haven't implemented the cached proxies yet*
Ideally though I'd prefer not to re-render the whole tree.


Saw react-tracked before, looked pretty cool. From glancing at https://github.com/dai-shi/react-tracked/blob/master/src/createUseTrackedState.js, can't see how you tackling the granular-reactive updates - can you elaborate?

**Comment by dai-shi** [comment]
> Don't think that would work as story={story} would always maintain the same identity

That was actually my concern too. I would personally prefer immutable values (or immutable references) so that `story={story}` works with React.memo (without `areEqual`).

Is it a design choice or a preference to use immutable references? Are there technical difficulties to take immutable values approach? I'm pretty interested in the immutability approach.

> can't see how you tackling the granular-reactive updates - can you elaborate?

There's no magic there. It's based on immutable values. So, React.memo works (with a limitation).
Another approach is to pass only `id`, which is a recommended pattern in Redux.
It would look like this:
```jsx
const Sotry = ({ storyId }) => {
  const story = useTrackedState().topStories[storyId]; // assuming `topStories` is an object rather than an array
  return <div>{story.title}</div>;
};
```

**Comment by samdenty** [comment]
Mutability was a design goal. It's important for gqless's client/server bi-directional reactivity model.

Aside from that, immutability is harder to use -

Stuff like `usePoll(query.name)` wouldn't work. You'd have to do `const name = usePoll(..`, be pretty messy.

`query.number++` would also not work. You'd have to do `query.number = currentQuery.number + 1`

**Comment by dai-shi** [comment]
Understood. That's a fair design choice.
I would explore the immutability approach as a challenge. Let me try what I can do on my end.

**Comment by dai-shi** [comment]
> I would explore the immutability approach as a challenge. Let me try what I can do on my end.

🎉  It works now as a PoC. https://github.com/dai-shi/gqless-hook
If someone were really interested in this approach, we would try to integrate more deeply. One of the biggest challenges is to provide `accessorInterceptors` from outside. That would ease development for React Concurrent Mode. (Note: MobX has the same limitation.)

**Comment by PabloSzx** [comment]
I just released a library that makes **useQuery** and **useMutation** hooks and is non-suspense based https://github.com/PabloSzx/gqless-hooks.
It gives promises of the requests, lazy query, mutation, (loading | error | done | waiting) state.

**Comment by dai-shi** [comment]
Let me leave a note here as I wasn't very clear in my last comment.
The difficulty with hooks is to avoid unnecessary renders. I wanted to solve it with React.memo, and did so with https://github.com/dai-shi/gqless-hook.

https://twitter.com/dai_shi/status/1243208372062547968
The screencast in this tweet shows renders with highlight. Only the first item re-renders when the points is changed to `-1`.

**Comment by PabloSzx** [comment]
Hi everyone, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .


It has special focus in the usage of hooks, as you could see here https://gqless.com/react/basic-usage thank you
