### ISSUE TITLE
Implicit any when schema has loops

### ISSUE THREAD

**Issue by vektah** [gqless/gqless#41]
When a schema loops typescript falls back to any.

eg

```graphql
type User {
  id: ID
  friends: [User!]!
}
```

> TS7023: 'User' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Comment by samdenty** [comment]
Which file is this in? If it's `schema.ts` then it should be ignored by the `ts-ignore-file` annotation (only in TS 3.7+)

If it's in the `types.ts` file, can you provide it

**Comment by PabloSzx** [comment]
Hi @vektah, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 

About this specific issue, it should be fixed in the new version.
