### ISSUE TITLE
Support for Next.js: getStaticProps / getServerProps

### ISSUE THREAD

**Issue by schickling** [gqless/gqless#44]
It seems gqless is currently not compatible with the upcoming `getStaticProps` / `getServerProps` feature of Next.js (see https://github.com/zeit/next.js/issues/9524). Would be great if gqless would support it out of the box. 💯

**Comment by samdenty** [comment]
dependant on https://github.com/samdenty/gqless/pull/39 + cache hydration

**Comment by schickling** [comment]
Great to see there's progress on this. Do you have any thoughts re the timeline for this?

**Comment by samdenty** [comment]
no timeline atm

**Comment by joltmode** [comment]
Hmm, but is it working with `getInitialProps`?

**Comment by PabloSzx** [comment]
Hi, I've been working on the support for Next.js on this project, and I appareantly found a way of doing it without too much added code, [here](https://github.com/PabloSzx/gqless/blob/local_link_gqless_react/packages/react/src/graphql/graphql.tsx#L149) you can see that we can use the **AppTree** prop in the data fetching functions in Next.js to render all the tree beforehand and let the rendering process do it's thing hydrating the cache.

I theory we could use getServerSideProps or getStaticProps but getStaticProps could be better for static optimization, but using getServerSideProps makes sure that the server side rendered version will be the same as the client side

**Comment by zenflow** [comment]
It seems that the title of this issue is inconsistent with the text body of the issue.. "Support for Next.js" is different from "Support for Next.js using getStaticProps / getServerProps".

Anyways.. This package works fine with Next.js & SSR, using the same approach as [the Next.js with-apollo example app](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) (which, yes @joltmode, uses `getInitialProps`). 

I made [a Next.js "with-gqless" example app](https://github.com/zenflow/next-with-gqless-example) you can use for reference. 

Any review of it would be appreciated (from you, yes you) since the plan is to eventually submit in a PR to the Next.js repo with this new example (with the redundant Apollo pages removed of course)

**Comment by PabloSzx** [comment]
Hi @zenflow, @schickling & @tomsseisums, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .

About this specific issue, the new version has SSR Helpers having special focus in functions like getStaticProps and getServerProps, please check https://gqless.com/react/ssr thank you
