### ISSUE TITLE
Persisted queries

### ISSUE THREAD

**Issue by lishine** [gqless/gqless#46]

**Comment by samdenty** [comment]
You can do this, but you have to implement it yourself.

You could modify the fetchQuery in generated/client.ts to first send a req with hash of the query over the network.
Then if it's not available on server, make another fetch call with actual query.

There's not really a way to 'statically' generate a query at build time - because there is multiple different ways a query could be generated.

**Comment by Daniel15** [comment]
I wrote some code for supporting Apollo-style automatic persisted queries with urql that might serve as inspiration:

https://github.com/Daniel15/urql-persisted-queries/blob/master/src/persistedFetchExchange.ts
https://github.com/Daniel15/urql-persisted-queries/blob/master/src/crypto.ts

It would be nice to support static persisted queries (Relay-style) too though!

**Comment by PabloSzx** [comment]
Hi @Daniel15, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 

About this specific issue, it's completely possible to implement, but in the short term we are going to focus in gettign the new version stable, and as mentioned before, it could even be possible to implement inside the query fetcher. thank you
