### ISSUE TITLE
will cursor based connections with pollers be supported?

### ISSUE THREAD

**Issue by smeijer** [gqless/gqless#76]
I've read the #43 issue, and one "issue" that I'm still having with apollo, is cursor-based pagination combined with polling. It's possible but requires a lot of boilerplate. The apollo team won't fix this (any time soon) 

> Closing because we don’t currently intend to make polling work with fetch more. The implementation would just be to difficult persevere
- https://github.com/apollographql/apollo-client/issues/1087#issuecomment-287458528

If this library provides that in a (better) way, it's definitely a unique selling point.

Having an example in the docs that shows how to implement pagination, with something like [`react-window`](https://react-window.now.sh), would be a killer.

**Comment by PabloSzx** [comment]
Hi @smeijer, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 

About this specific issue, we would really like to implement this feature, but in the short-term we will be focusing in getting the new version stable, feel free to create a new issue again later

**Comment by smeijer** [comment]
Hi @PabloSzx. Totally understand! I'm excited about this new release. Missing support for mutations was something that was holding me off. This is amazing!

Regarding this ticket. What stops you from simply keeping it open?

**Comment by PabloSzx** [comment]
> Regarding this ticket. What stops you from simply keeping it open?

It was mainly a matter of cleanup since most of the previous issues were related to the previous version, this new version is a complete re-write.

I tested the new version with cursor pagination and it works great, and currently for simplicity only ["useTransactionQuery"](https://gqless.com/react/query#usetransactionquery) enables polling, but in practice using react binding "useRefetch" or the core ["refetch"](https://gqless.com/core/basic-usage#refetch) would work fine
