### ISSUE TITLE
Any support for Nuxt.js?

### ISSUE THREAD

**Issue by avaldevilap** [gqless/gqless#99]

**Comment by selfagency** [comment]
Please add Vue and Nuxt support!

**Comment by PabloSzx** [comment]
Hi @avaldevilap & @selfagency, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our discord server, to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .

About this specific feature request, it's completely feasible due to the new design, feel free to open a new issue requesting it and discussing it's implementation via the same issue, or in our [discord server](https://discord.gg/2gy8ZQxnGk)

**Comment by wobsoriano** [comment]
Haven't tried with Nuxt, but it should work with composition-api installed https://github.com/wobsoriano/vue-gqty
